version: '3.8'

services:
  mongodb:
    image: mongo:7.0.4
    ports:
      - '27017:27017'
    volumes:
      - mongo:/data/db

  server:
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    environment:
      MONGO_DB_URL: mongodb://host.docker.internal:27017
      DB_NAME: mydb
      PORT: 3005
    depends_on:
      - mongodb
    ports:
      - 3005:3005

volumes:
  mongo:
